# Generated by Django 3.1.6 on 2021-04-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartdata', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('sex', models.CharField(max_length=122)),
                ('survived', models.BooleanField()),
                ('age', models.FloatField()),
                ('ticket_class', models.PositiveSmallIntegerField()),
                ('embarked', models.CharField(max_length=122)),
            ],
        ),
    ]
